//Constants 🔒
// Catálogo completo
export const catalogo = {
  armas: {
    "Daga Oxidada": {
      precio: 100,
      ataque: 5,
      defensa: 0,
      suerte: 0,
      rareza: "Común",
    },
    "Espada de Madera": {
      precio: 150,
      ataque: 8,
      defensa: 0,
      suerte: 0,
      rareza: "Común",
    },
    "Hacha de Piedra": {
      precio: 200,
      ataque: 10,
      defensa: 0,
      suerte: 0,
      rareza: "Común",
    },
    "Sable Curvo": {
      precio: 300,
      ataque: 15,
      defensa: 0,
      suerte: 0.05,
      rareza: "Raro",
    },
    "Katana de Fuego": {
      precio: 500,
      ataque: 20,
      defensa: 0,
      suerte: 0.1,
      rareza: "Raro",
    },
    "Lanza del Dragón": {
      precio: 800,
      ataque: 25,
      defensa: 0,
      suerte: 0.15,
      rareza: "Épico",
    },
    "Espada del Caos": {
      precio: 1200,
      ataque: 30,
      defensa: 5,
      suerte: 0.2,
      rareza: "Épico",
    },
    "Hacha del Trueno": {
      precio: 1500,
      ataque: 35,
      defensa: 0,
      suerte: 0.25,
      rareza: "Legendario",
    },
    "Guadaña Sombría": {
      precio: 2000,
      ataque: 40,
      defensa: 0,
      suerte: 0.3,
      rareza: "Legendario",
    },
    "Filo del Infinito": {
      precio: 3000,
      ataque: 50,
      defensa: 10,
      suerte: 0.4,
      rareza: "Legendario",
    },
  },
  armaduras: {
    "Túnica Rota": {
      precio: 100,
      ataque: 0,
      defensa: 5,
      suerte: 0,
      rareza: "Común",
    },
    "Cota de Cuero": {
      precio: 150,
      ataque: 0,
      defensa: 8,
      suerte: 0,
      rareza: "Común",
    },
    "Peto de Hierro": {
      precio: 200,
      ataque: 0,
      defensa: 10,
      suerte: 0,
      rareza: "Común",
    },
    "Armadura de Escamas": {
      precio: 300,
      ataque: 0,
      defensa: 15,
      suerte: 0.05,
      rareza: "Raro",
    },
    "Cota de Malla": {
      precio: 500,
      ataque: 0,
      defensa: 20,
      suerte: 0,
      rareza: "Raro",
    },
    "Placas de Obsidiana": {
      precio: 800,
      ataque: 5,
      defensa: 25,
      suerte: 0.1,
      rareza: "Épico",
    },
    "Escudo de Titanio": {
      precio: 1200,
      ataque: 0,
      defensa: 30,
      suerte: 0.15,
      rareza: "Épico",
    },
    "Armadura del Fénix": {
      precio: 1500,
      ataque: 10,
      defensa: 35,
      suerte: 0.2,
      rareza: "Legendario",
    },
    "Manto Estelar": {
      precio: 2000,
      ataque: 0,
      defensa: 40,
      suerte: 0.25,
      rareza: "Legendario",
    },
    "Piel del Void": {
      precio: 3000,
      ataque: 15,
      defensa: 50,
      suerte: 0.3,
      rareza: "Legendario",
    },
  },
  amuletos: {
    "Colgante de Piedra": {
      precio: 100,
      ataque: 2,
      defensa: 2,
      suerte: 0.05,
      rareza: "Común",
    },
    "Anillo de Bronce": {
      precio: 150,
      ataque: 3,
      defensa: 3,
      suerte: 0.05,
      rareza: "Común",
    },
    "Talismán de Madera": {
      precio: 200,
      ataque: 5,
      defensa: 0,
      suerte: 0.1,
      rareza: "Común",
    },
    "Amuleto de la Suerte": {
      precio: 300,
      ataque: 5,
      defensa: 5,
      suerte: 0.15,
      rareza: "Raro",
    },
    "Reloj de Arena": {
      precio: 500,
      ataque: 0,
      defensa: 10,
      suerte: 0.2,
      rareza: "Raro",
    },
    "Ojo del Kraken": {
      precio: 800,
      ataque: 10,
      defensa: 5,
      suerte: 0.25,
      rareza: "Épico",
    },
    "Corazón de Fuego": {
      precio: 1200,
      ataque: 15,
      defensa: 0,
      suerte: 0.3,
      rareza: "Épico",
    },
    "Cristal Lunar": {
      precio: 1500,
      ataque: 10,
      defensa: 10,
      suerte: 0.35,
      rareza: "Legendario",
    },
    "Esencia del Dragón": {
      precio: 2000,
      ataque: 20,
      defensa: 15,
      suerte: 0.4,
      rareza: "Legendario",
    },
    "Orbe del Destino": {
      precio: 3000,
      ataque: 25,
      defensa: 20,
      suerte: 0.5,
      rareza: "Legendario",
    },
  },
  accesorios: {
    "Capa Raída": {
      precio: 100,
      ataque: 0,
      defensa: 3,
      suerte: 0.05,
      rareza: "Común",
    },
    "Botas Gastadas": {
      precio: 150,
      ataque: 2,
      defensa: 2,
      suerte: 0.05,
      rareza: "Común",
    },
    "Guantes de Cuero": {
      precio: 200,
      ataque: 5,
      defensa: 0,
      suerte: 0,
      rareza: "Común",
    },
    "Cinturón de Fuerza": {
      precio: 300,
      ataque: 8,
      defensa: 0,
      suerte: 0.1,
      rareza: "Raro",
    },
    "Gafas de Visión": {
      precio: 500,
      ataque: 0,
      defensa: 5,
      suerte: 0.15,
      rareza: "Raro",
    },
    "Collar de Escamas": {
      precio: 800,
      ataque: 10,
      defensa: 5,
      suerte: 0.2,
      rareza: "Épico",
    },
    "Anillo del Fénix": {
      precio: 1200,
      ataque: 15,
      defensa: 0,
      suerte: 0.25,
      rareza: "Épico",
    },
    "Capa del Viento": {
      precio: 1500,
      ataque: 10,
      defensa: 10,
      suerte: 0.3,
      rareza: "Legendario",
    },
    "Botas del Trueno": {
      precio: 2000,
      ataque: 20,
      defensa: 5,
      suerte: 0.35,
      rareza: "Legendario",
    },
    "Corona del Rey Caído": {
      precio: 3000,
      ataque: 25,
      defensa: 15,
      suerte: 0.4,
      rareza: "Legendario",
    },
  },
  mascotas: {
    "Rana Fantasma": {
      precio: 200,
      ataque: 5,
      defensa: 5,
      suerte: 0.1,
      rareza: "Común",
      evolucion: "Rana Espectral",
    },
    "Gato Callejero": {
      precio: 250,
      ataque: 8,
      defensa: 3,
      suerte: 0.05,
      rareza: "Común",
      evolucion: "Gato Sombra",
    },
    "Pez Inútil": {
      precio: 100,
      ataque: 1,
      defensa: 1,
      suerte: 0,
      rareza: "Común",
      evolucion: "Dragón Marino",
    }, // Magikarp
    "Cuervo Rancio": {
      precio: 300,
      ataque: 10,
      defensa: 5,
      suerte: 0.15,
      rareza: "Raro",
      evolucion: "Cuervo del Abismo",
    },
    "Serpiente de Lava": {
      precio: 500,
      ataque: 15,
      defensa: 5,
      suerte: 0.2,
      rareza: "Raro",
      evolucion: "Víbora Ígnea",
    },
    "Fénix Bebé": {
      precio: 800,
      ataque: 20,
      defensa: 10,
      suerte: 0.25,
      rareza: "Épico",
      evolucion: "Fénix Ardiente",
    },
    "Grifo Joven": {
      precio: 1200,
      ataque: 25,
      defensa: 15,
      suerte: 0.3,
      rareza: "Épico",
      evolucion: "Grifo Celestial",
    },
    Quimera: {
      precio: 1500,
      ataque: 30,
      defensa: 20,
      suerte: 0.35,
      rareza: "Legendario",
      evolucion: "Quimera Primordial",
    },
    "Kraken Pequeño": {
      precio: 2000,
      ataque: 35,
      defensa: 25,
      suerte: 0.4,
      rareza: "Legendario",
      evolucion: "Kraken Abisal",
    },
    "Unicornio Sombrío": {
      precio: 3000,
      ataque: 40,
      defensa: 30,
      suerte: 0.5,
      rareza: "Legendario",
      evolucion: "Unicornio del Vacío",
    },
  },
};
// Almacenamiento temporal para las adivinanzas activas
export const adivinanzasActivas = new Map();

export const predicciones = {
  amor: {
    positivas: [
      "💘 El amor de tu vida está más cerca de lo que piensas... ¡Podría ser alguien que ya conoces!",
      "💝 Las estrellas indican que encontrarás un amor verdadero y duradero muy pronto",
      "💖 Una persona especial está pensando en ti ahora mismo",
      "💗 Tu próxima historia de amor será digna de una película romántica",
      "💓 Alguien de [signo zodiacal aleatorio] cambiará tu vida amorosa",
    ],
    neutras: [
      "💌 El amor llegará cuando dejes de buscarlo",
      "🎭 Una amistad podría convertirse en algo más",
      "🌟 Tu persona ideal aparecerá en el momento menos esperado",
      "🔮 El destino tiene preparada una sorpresa romántica para ti",
    ],
    advertencias: [
      "⚠️ Cuidado con los amores del pasado, no todo lo que brilla es oro",
      "🚫 No te apresures en tomar decisiones amorosas importantes",
      "⏳ La paciencia será tu mejor aliada en el amor",
      "🎭 Alguien no es quien dice ser, mantén los ojos abiertos",
    ],
  },
  fortuna: {
    positivas: [
      "💰 ¡Una gran fortuna está en tu futuro próximo!",
      "💎 Una inversión inesperada te traerá grandes beneficios",
      "🎰 La suerte está de tu lado, aprovecha las oportunidades",
      "💸 Un proyecto olvidado te traerá prosperidad",
    ],
    neutras: [
      "📈 Tus finanzas mejorarán gradualmente",
      "🎲 Una decisión financiera importante se acerca",
      "💼 Una oportunidad laboral cambiará tu situación económica",
      "🌟 El éxito llegará a través de un camino inesperado",
    ],
    advertencias: [
      "⚠️ Cuidado con gastos innecesarios en los próximos días",
      "🚫 No prestes dinero en las próximas semanas",
      "⏳ Espera el momento adecuado para inversiones importantes",
      "🎭 No todo lo que parece una oportunidad lo es realmente",
    ],
  },
  futuro: {
    positivas: [
      "✨ Un cambio positivo transformará tu vida en los próximos meses",
      "🌟 El universo conspira a tu favor, grandes cosas se acercan",
      "🎯 Tus metas más importantes están a punto de realizarse",
      "🚀 Un viaje inesperado cambiará tu perspectiva de vida",
    ],
    neutras: [
      "🎭 El destino te tiene preparadas algunas sorpresas",
      "🌈 Un encuentro casual marcará un antes y después",
      "🎪 La vida te presentará nuevas y emocionantes aventuras",
      "🎨 Es momento de reinventarte y seguir tus sueños",
    ],
    advertencias: [
      "⚠️ Mantén los ojos abiertos ante cambios repentinos",
      "🔮 No todas las oportunidades son lo que parecen",
      "⏳ La paciencia será crucial en los próximos meses",
      "🎭 Alguien cercano podría necesitar tu ayuda pronto",
    ],
  },
};

export const eventos = [
  {
    mensaje: "💼 ¡Conseguiste un aumento en el trabajo!",
    cambios: { dinero: 500, felicidad: 10, estres: 5 },
    requiereTrabajo: true, // Requiere tener profesión
  },
  {
    mensaje: "🏃 Fuiste al gimnasio",
    cambios: { salud: 5, energia: -10, estres: -5 },
  },
  {
    mensaje: "📚 Estudiaste algo nuevo",
    cambios: { inteligencia: 5, energia: -5, estres: 5 },
  },
  {
    mensaje: "🎉 ¡Felicidades! Ganaste un premio sorpresa",
    cambios: { felicidad: 10, estres: -5 },
  },
  {
    mensaje: "🚫 ¡Te quedaste dormido todo el día!",
    cambios: { energia: -20, estres: 10 },
  },
  {
    mensaje: "🍕 Pediste pizza gratis en el chat",
    cambios: { dinero: -10, felicidad: 15, salud: -5 },
  },
  {
    mensaje: "🎮 ¡Jugaste videojuegos toda la noche!",
    cambios: { inteligencia: 3, energia: -15, felicidad: 10 },
  },
  {
    mensaje: "🐶 Adoptaste un perro virtual",
    cambios: { felicidad: 20, dinero: -100 },
  },
  {
    mensaje: "💥 ¡Tuviste un accidente gracioso en el trabajo!",
    cambios: { estres: 15, salud: -10 },
    requiereTrabajo: true,
  },
  {
    mensaje: "🌧️ Te mojaste bajo la lluvia",
    cambios: { salud: -5, felicidad: -5, estres: 5 },
  },
  {
    mensaje: "🎤 Cantaste en karaoke y fallaste",
    cambios: { felicidad: -10, estres: 5 },
  },
  {
    mensaje: "🍳 Cocinaste un desastre, pero te ríes",
    cambios: { felicidad: 5, salud: -5 },
  },
  {
    mensaje: "🚗 Ganaste una carrera de carritos de supermercado",
    cambios: { dinero: 200, felicidad: 15 },
  },
  {
    mensaje: "📱 Te volvieron loco con memes",
    cambios: { inteligencia: 2, felicidad: 10, estres: 5 },
  },
  {
    mensaje: "🏖️ Pasaste un día en la playa virtual",
    cambios: { salud: 10, energia: -5, felicidad: 20 },
  },
  {
    mensaje: "👻 Viste una película de terror",
    cambios: { felicidad: -5, estres: 10 },
  },
  {
    mensaje: "💃 Bailaste con un NPC torpe",
    cambios: { felicidad: 10, energia: -10 },
  },
  {
    mensaje: "🎁 Recibiste un regalo misterioso",
    cambios: { dinero: 300, estres: -5 },
  },
  {
    mensaje: "🤡 Hiciste un chiste malo en el chat",
    cambios: { felicidad: -5, social: 5 },
  },
  {
    mensaje: "🌳 Plantaste un árbol digital",
    cambios: { felicidad: 10, estres: -5, dinero: -50 },
  },
  {
    mensaje: "🎸 Tocaste la guitarra como rockstar",
    cambios: { felicidad: 15, energia: -10 },
  },
];

// Frases místicas para dar ambiente
export const frasesIntro = [
  "🔮 Los astros se han alineado para revelarte que...",
  "✨ Las cartas del tarot me muestran que...",
  "🌟 Los espíritus susurran que tu destino...",
  "💫 Las estrellas han hablado, y dicen que...",
  "🎆 El universo me ha revelado que...",
  "🌙 En la luna llena se puede ver que...",
];

// Consejos místicos para finalizar
export const consejosFinales = [
  "👁️ Mantén tu mente y corazón abiertos a las señales del universo",
  "🙏 La meditación te ayudará a encontrar tu camino",
  "🍀 La buena fortuna sonríe a quienes mantienen pensamientos positivos",
  "🌟 Confía en tu intuición, ella nunca te engañará",
  "💫 El universo conspira a tu favor, solo debes creer",
];

// Base de datos de adivinanzas
export const adivinanzas = [
  {
    pregunta:
      "Tengo ciudades, pero no casas. Tengo montañas, pero no árboles. Tengo agua, pero no peces. Tengo carreteras, pero no coches. ¿Qué soy?",
    respuesta: "mapa",
    pista: "Me usan para navegar 🧭",
  },
  {
    pregunta:
      "¿Qué tiene llaves pero ninguna cerradura, espacio pero ninguna habitación, y puedes entrar pero no puedes salir?",
    respuesta: "teclado",
    pista: "Lo usas para escribir en la computadora ⌨️",
  },
  {
    pregunta:
      "Cuando me necesitas, me tiras. Cuando ya no me necesitas, me recoges. ¿Qué soy?",
    respuesta: "ancla",
    pista: "Soy amiga de los marineros ⚓",
  },
  {
    pregunta: "¿Qué es aquello que si nombras, desaparece?",
    respuesta: "silencio",
    pista: "Shhhhh... 🤫",
  },
  // Añade más adivinanzas aquí
];

export const premios = [
  { mensaje: "🎉 Ganaste 100 monedas", dinero: 100 },
  { mensaje: "😢 Perdiste 50 monedas", dinero: -50 },
  { mensaje: "😊 Ganaste 10 de felicidad", felicidad: 10 },
  { mensaje: "😰 Ganaste 5 de estrés", estres: 5 },
  { mensaje: "💰 Ganaste 500 monedas", dinero: 500 },
  { mensaje: "💸 Perdiste 200 monedas", dinero: -200 },
  { mensaje: "💪 Ganaste 15 de energía", energia: 15 },
  { mensaje: "🤕 Perdiste 10 de salud", salud: -10 },
  { mensaje: "🧠 Ganaste 5 de inteligencia", inteligencia: 5 },
  { mensaje: "👥 Aumentaste tu vida social en 8", social: 8 },
  { mensaje: "🏥 Perdiste 15 de salud", salud: -15 },
  { mensaje: "⏳ Envejeciste 1 año", edad: 1 },
];

export const insultos = [
  "¿Eres tonto o jugaste el tutorial 10 veces y aún perdiste?",
  "Te mataron en el lobby, y era PvE.",
  "Tu aim da más pena que un creeper sin pólvora.",
  "Eres tan lento que hasta los NPCs te hacen speedrun.",
  "Tienes menos skill que un aldeano en PvP.",
  "Eres el tipo que se cae en el parkour del spawn.",
  "Tu build parece hecha por un bot en su primer día.",
  "Te rushean y saludas en vez de defender.",
  "Tienes menos reflejos que un ping de 999ms.",
  "Tu IQ es más bajo que tus FPS en Ultra.",
  "Tu main es morir primero y lo haces excelente.",
  "Eres el que en ranked se va AFK a hacer sándwiches.",
  "Confundes una granada con un heal.",
  "Juegas tan mal que los minions te hacen emote.",
  "Tu combo es: fallar, morir y echarle la culpa al lag.",
  "Ni el tutorial te quiso enseñar.",
  "Tu joystick tiene más control que tú.",
  "Tienes la puntería de un Stormtrooper borracho.",
  "Campeas tanto que ya te mandaron una factura de renta.",
  "Te caíste del mapa en modo espectador.",
  "Tu KD es negativo hasta en Minecraft.",
  "Haces más ruido que un escuadrón sin silenciador.",
  "Eres tan inútil que en Among Us te echan siendo tripulante.",
  "En el LoL tu rol es el ward… sin visión.",
  "Te escondes en Fortnite y aún así te encuentran con pico.",
  "Juegas como si usaras control de Fisher Price.",
  "Eres ese que en Warzone se rompe las piernas al aterrizar.",
  "Tu rotación confunde hasta al GPS.",
  "Tu teclado te pide que dejes de apretarlo sin sentido.",
  "Eres el jugador perfecto… para el equipo enemigo.",
];

export const cumplidos = [
  "Eres como un bug en el juego: molesto, pero todos te notan.",
  "Jugaste tan bien que hasta el lag se rindió.",
  "Tienes tanto carisma que los bots quieren agregarte.",
  "No eres el mejor, pero haces reír mientras pierdes.",
  "Tu voz es tan única que hasta el micro se confunde.",
  "Tienes una actitud tan positiva que ni el team te puede bajonear (aunque lo intentan).",
  "Juegas con tanto corazón que da pena verte perder.",
  "No sabes jugar, pero eres lindo, y eso equilibra.",
  "Eres el MVP… del equipo enemigo.",
  "Eres tan especial que hasta el respawn te extraña.",
  "Tienes un talento natural… para regalar kills.",
  "Tu gameplay es como el arte abstracto: nadie lo entiende, pero todos lo miran.",
  "Eres tan constante… en morir.",
  "Juegas tan tranquilo que ni te afecta perder… porque ya es costumbre.",
  "Tienes tanto estilo que ni ganar te importa.",
  "Eres como un minijefe: molestas, pero no representas peligro.",
  "Eres la prueba de que la actitud vale más que el skill.",
  "Eres tan amable que dejas ganar a todos sin decirlo.",
  "Siempre estás ahí… aunque no hagas mucho.",
  "Eres un ejemplo… de cómo no jugar, pero con clase.",
  "Tienes ese 'algo' que hace que todos te recuerden (y se pregunten cómo sigues en el team).",
  "Tu presencia ilumina la partida… como una granada flash.",
  "Tienes una energía tan rara que hasta los bugs te siguen.",
  "Pareces AFK, pero no… solo eres tú jugando.",
  "Tienes una conexión tan fiel al lag que ya parecen pareja.",
  "Juegas como si no hubiera consecuencias, y eso es admirable… supongo.",
  "Tienes un corazón de oro… lástima que no puedas lootearlo.",
  "Tu determinación es tan fuerte como tu falta de puntería.",
  "No todos pueden ser buenos, pero pocos lo hacen con tanta gracia como tú.",
  "Eres un ícono del caos: no ayudas mucho, pero sin ti sería aburrido.",
];
export const factos = [
  "Si juegas mal y le echas la culpa al lag, el lag se ofende.",
  "El que dice 'yo solo juego por diversión' es el primero en tiltearse.",
  "El main support que no cura, pero exige respeto.",
  "Decir GG al final no arregla tu pésima actitud.",
  "Si usas skin cara y juegas mal, es pay to embarrass.",
  "Si siempre estás 'probando algo nuevo', tal vez solo eres malo.",
  "Gritar por el micro no mejora tu skill, pero sí baja el volumen del team.",
  "Si llevas 2 kills y 10 muertes… no, no estás 'jugando objetivo'.",
  "El que más critica al equipo, es el que menos aporta.",
  "Decir que eres 'main' de algo no te hace bueno en eso.",
  "Tu KD dice más de ti que tu biografía en Tinder.",
  "Si no sabes quién es el tóxico del grupo… eres tú.",
  "Usar hacks no te hace pro, solo más fácil de banear.",
  "Los que piden 1v1 siempre pierden y luego desaparecen.",
  "Tu mouse gamer no compensa tu falta de habilidad.",
  "Jugar 8 horas no te hace streamer, solo desempleado con buen internet.",
  "Si usas alt+f4 como estrategia, eres un genio… del abandono.",
  "Si tienes excusa para cada muerte, el problema eres tú.",
  "El que usa voz de macho alfa en el chat, vive con su mamá.",
  "Más vale ping alto con buena actitud que ping bajo con ego.",
  "Si dices 'yo solía ser bueno', nadie te cree.",
  "Ser diamante en un juego no te da derecho a tratar mal a bronces… bueno, tal vez sí, pero sigue estando mal.",
  "Tu waifu no te salvará del reporte.",
  "Si siempre juegas con tus compas y sigues perdiendo… tal vez el problema es el escuadrón.",
  "Si dices 'ya lo tenía muerto', el universo te está viendo raro.",
  "Si entras a flamear a un streamer, es porque tu vida no tiene respawn.",
  "No eres 'chistoso', solo repites lo que viste en TikTok.",
  "El que dice 'soy chill' es el primero en tirar rage quit.",
  "Más horas en el juego no significan más habilidades, solo más tiempo perdido.",
  "Tener voz grave no te hace líder, te hace narrador de tus fracasos.",
];

export const animales = [
  "Ajolote con ansiedad social crónica",
  "Capibara con deudas emocionales",
  "Ornitorrinco que le teme al agua",
  "Narval con cuerno chueco por usar casco",
  "Cacatúa que solo repite spoilers",
  "Lemur con insomnio por culpa del café",
  "Tapir con intolerancia a los memes",
  "Wombat con dislexia emocional",
  "Zorro ártico que odia el frío",
  "Pangolín con alergia a su propia armadura",
  "Tardígrado que siempre llega tarde",
  "Caracal que no le gusta cazar, solo llora",
  "Mono ardilla con apego tóxico a su banana",
  "Mantis religiosa con crisis existencial",
  "Colibrí con vértigo en pleno vuelo",
  "Castor con deficiencia renal y sueños rotos",
  "Fosa con adicción a los doritos",
  "Pez payaso con fobia a las multitudes",
  "Guacamayo que solo canta reggaetón",
  "Camarón mantis con miopía selectiva",
  "Armadillo claustrofóbico",
  "Aye-aye que solo ve colores tristes",
  "Iguana con déficit de atención (y de afecto)",
  "Murciélago frugívoro con miedo a las frutas",
  "Dragón de Komodo con autoestima frágil",
  "Okapi con doble vida en LinkedIn",
  "Suricata con TOC por alinear granos de arena",
  "Antílope saiga con asma nerviosa",
  "Cangrejo yeti con complejo de inferioridad",
  "Pez luna con pensamientos circulares",
];

export const superHeroes = [
  "Calcetín Supremo – Puede volverse invisible, pero solo del tobillo para abajo.",
  "Capitán Siesta – Se duerme en cualquier situación, pero mientras sueña predice el futuro.",
  "El Hombre Llama-Domingos – Solo puede invocar fuego los domingos y con resaca.",
  "Señor Resorte – Rebota sin control, especialmente en situaciones serias.",
  "La Sombra Desorientada – Se teletransporta, pero nunca sabe a dónde.",
  "Doña Hipo – Cada hipo lanza ondas sónicas destructivas (y vergonzosas).",
  "El Marmota – Se esconde nueve meses y aparece con spoilers.",
  "Chico Moco – Lanza proyectiles nasales pegajosos y altamente tóxicos.",
  "La Cabra Psíquica – Lee la mente… pero solo de otros animales.",
  "Hombre Microondas – Calienta todo a su alrededor, pero solo en 30 segundos exactos.",
  "Súper IT – Repara WiFi con la mente, pero solo si el router es marca TP-Link.",
  "Mujer Panqueque – Puede volverse completamente plana, pero pierde la memoria al hacerlo.",
  "El Volador de Sillones – Vuela… pero solo en un sillón viejo y ruidoso.",
  "Doctor Gallina – Tiene visión láser, pero solo cuando cacarea.",
  "Capitán Látigo Emocional – Manipula sentimientos, pero solo para provocar drama.",
  "Chico Espejo – Refleja cualquier ataque, pero también cualquier insulto.",
  "El Evaporador – Puede evaporar líquidos… incluyendo su propio café.",
  "Señora Pestaña – Lanza vientos huracanados con sus pestañeos, pero solo una vez al día.",
  "Niño Olor – Su aroma cambia según su estado de ánimo (y asusta a los enemigos).",
  "Don Refrigerador – Controla el frío, pero debe estar enchufado.",
  "La Rata Épica – Tiene superfuerza, pero solo cuando nadie la está mirando.",
  "Capitán Tanga – Se vuelve invulnerable al sentirse humillado.",
  "El Deslizador – Siempre se resbala… pero esquiva todo sin querer.",
  "Galleta Cósmica – Se convierte en galleta para infiltrarse en cualquier lugar… y casi siempre se lo comen.",
  "Niña Spoiler – Puede predecir el final de cualquier cosa… incluso antes de que empiece.",
  "Profesor Eco – Repite todo lo que dices, pero con voz épica y eco.",
  "El Hombre Playlist – Manipula emociones a través de música, pero solo si es reggaetón lento.",
  "Señora Zoom – Se mueve rapidísimo, pero siempre se pasa de su destino.",
  "Cactus Boy – Tiene púas indestructibles, pero abraza demasiado.",
  "El Ronco Misterioso – Su voz puede destruir estructuras, pero luego queda afónico por 3 días.",
];

export const respuesta = [
  "Sí",
  "No",
  "Quizás",
  "Tal vez",
  "Definitivamente",
  "No lo creo",
  "Posiblemente",
  "Dudo de ello",
  "Sí, definitivamente",
  "No, definitivamente",
];
